<a href="https://colab.research.google.com/github/Pedro-Ivo-Florentino/Exerc-cios-Gradua-o/blob/main/UNOPAR_AULAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercício 1:

# **Repositório** dos exercícios realizados na disciplina de Linguagem de Programção no Curso de Graduação em Arquitetura de Dados da Unopar.

Exercício 1:

In [ ]:
texto = 'Aprendendo Python na disciplina Linguagem de Programação.'
print(f'A palavra Python está inserida na variável texto? = {"Python" in texto}')
print(f'Quantas vezes aparece a letra y no texto? {texto.count("y")}')
print(f'As cinco primeiras letras são: {texto[0:5]}.')


A palavra Python está inserida na variável texto? = True
Quantas vezes aparece a letra y no texto? 1
As cinco primeiras letras são: Apren.


Exercício 2:

In [ ]:
texto = 'Aprendendo Python na disciplina Linguagem de Programação.'
print(f'O tamnho do texto, considerando os espaços em branco, é: {len(texto)}')
print(f'O texto separado por palavras fica: {texto.split()}')
palavras = texto.split()
print(f'A quantidade de palvras no texto é de: {len(palavras)}')
palavras[0:2] # mostra as palvras da posição 0 até a posição 2.
texto_virgula = ("Aprendendo, Python, na, disciplina, Linguagem, de, Programação.")
print(texto_virgula.split(","))


O tamnho do texto, considerando os espaços em branco, é: 57
O texto separado por palavras fica: ['Aprendendo', 'Python', 'na', 'disciplina', 'Linguagem', 'de', 'Programação.']
A quantidade de palvras no texto é de: 7
['Aprendendo', ' Python', ' na', ' disciplina', ' Linguagem', ' de', ' Programação.']


Exercício 3:

In [ ]:
vogais = ('a', 'e', 'i', 'o', 'u')
for letra in vogais:
    print(f'A posição da vogal {letra.upper()} é: {vogais.index(letra)+1}')
    

A posição da vogal A é: 1
A posição da vogal E é: 2
A posição da vogal I é: 3
A posição da vogal O é: 4
A posição da vogal U é: 5


Exercício 4:


In [ ]:
linguagem = ('Python JavaScript C++ C# Java Go Cobol Swift c').split()
print(f'Essa é a variável antes da listcomp: {linguagem}')
linguagem = [item.lower() for item in linguagem]
print('Depois da listcom: ', linguagem)


Essa é a variável antes da listcomp: ['Python', 'JavaScript', 'C++', 'C#', 'Java', 'Go', 'Cobol', 'Swift', 'c']
Depois da listcom:  ['python', 'javascript', 'c++', 'c#', 'java', 'go', 'cobol', 'swift', 'c']


Exercício 5:

In [ ]:
numeros = list(range(0,100))
numeros_pares = list(filter(lambda x: x % 2 != 0, numeros))
print(numeros_pares)


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


Exercício 5:

In [ ]:
vogais = ('a', 'e', 'i', 'o', 'u')
for posicao, valor, in enumerate(vogais):# A função enumerate retorna uma tupla cujo o primeiro elemento
# é a posição indice e o segundo elemento é o seu valor. 
    print(f'A posição da vogal é: {posicao} e o seu valor é: {valor.upper()}')
print(f'O tipo dos objetos da variável vogais é: {type(vogais)}')


A posição da vogal é: 0 e o seu valor é: A
A posição da vogal é: 1 e o seu valor é: E
A posição da vogal é: 2 e o seu valor é: I
A posição da vogal é: 3 e o seu valor é: O
A posição da vogal é: 4 e o seu valor é: U
O tipo dos objetos da variável vogais é: <class 'tuple'>


Exercício **6**:

In [ ]:
vogais_1 = {'aeiou'} # sem uso de construtor
print(type(vogais_1))# construtor em string
vogais_2 = set('aeiouaoueaeiouaeiou')
print(vogais_2, type(vogais_2))
vogais_3 = set(['a','e','i','o','u'])#construtor com lista
print(vogais_3)
print(type(vogais_3))
vogais_4 = set(('a','e','i','o','u'))#construtor com tuplas
print(vogais_4)
print(type(vogais_4))
print(set('Banana'))


<class 'set'>
{'i', 'u', 'a', 'e', 'o'} <class 'set'>
{'i', 'u', 'a', 'e', 'o'}
<class 'set'>
{'i', 'u', 'a', 'e', 'o'}
<class 'set'>
{'B', 'a', 'n'}


Exercício 7:

In [ ]:
# Exemplo 1 com criação de dicionário vazio com atribuição posterior de chave e valoo

dicio_1 = {}
dicio_1['Nome'] = 'João'
dicio_1['Idade'] = 30

# Exemplo 2 criação de dicionário usando um par elementos na forma, chave : valor

dicio_2 = {'Nome': 'João', 'Idade': 30}

# Exemplo 3 com criação de dicionário usando tuplas. Cada tupla represente um par chabe : valor.

dicio_3 = dict([('Nome', 'João'), ('Idade', 30)])

#Exemplo 4 com criação de dicionário com a função built-in zip() e duas listas, uma coa a chave, outra com valor.

dicio_4 = dict(zip(['Nome', 'Idade'], ['João', 30]))

print(dicio_1 == dicio_2 == dicio_3 == dicio_4)# testando se os valores são equivalentes 


True


Exercício 8:

In [ ]:
# Objetos do tipo array Nunpay

import numpy as np
matriz_1_1 = np.array([1,2,3])# Cria matriz 1 linha e uma coluna
#matriz_2_2 = np.array([1,2],[3,4])# Cria matriz 2 linhas e 2 colunas
matriz_3_2 = np.array([[1,2],[3,4],[5,6]])# Cria matriz 3 linhas e 2 colunas
matriz_2_3 = np.array([[1,2,3],[4,5,6]])# Cria matriz 2 linhas e 3 colunas
print('\n',matriz_1_1)
print('\n',matriz_2_2)
print('\n',matriz_3_2)
print('\n',matriz_2_3)



 [1 2 3]

 [[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 3]
 [4 5 6]]


Algoritmos de busca


Exercício 9:

In [ ]:

def executar_busca_linear(lista,valor): # Criamos a função com os parámetos desejados
    for elemento in lista:
        if valor == elemento:
            return True
    return False

import random
lista = random.sample(range(100),20)#Dentro do range de 0 a 100 serão buscados 20 valores de forma aleatória
print(sorted(lista)) #Imprime a lista de forma ordenada
executar_busca_linear(lista,10) #Trazemos a função que buscará o valor 10 dentro dela


[6, 11, 15, 20, 28, 30, 33, 34, 37, 47, 49, 52, 70, 71, 73, 75, 76, 84, 86, 92]


False

Exercício 10:

In [ ]:
# Buscando valores em uma string
valores = 'abcdefghijklmnopqrstuvwxyz'
resultado = valores.index('k')
print(f'A posição do valor informado é a {resultado+1}ª posição.')#Acrescentei o +1, para compensar a leitura de índice realizada pelo python.


A posição do valor informado é a 11ª posição.


Exercício 11:

In [ ]:
#Busca binária

def executar_busca_binaria(lista, valor):
    minimo = 0
    maximo = len(lista) - 1
    while minimo <= maximo:
        meio = (minimo + maximo) // 2 # Encontra o elemento que divide a lista ao meio
        if valor < lista[meio]:
            maximo = meio - 1 # Verifica se o valor procurado está a esquerda ou direita do valor central
        elif valor > lista[meio]:
            minimo = meio + 1
        else:
            return True # Se o valor for encontrado para aqui
    return False # Caso o valor não for encontrado
lista = list(range(1,50))
print(lista)
print('\n',executar_busca_binaria(lista = lista, valor = 10))
print('\n',executar_busca_binaria(lista = lista, valor = 20))


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]

 True

 True


Exercício 12:

In [ ]:
#As listas em Python possuem um método embutido sort() que modifica a lista em si. 
#Há também a função embutida sorted() que constrói uma nova lista ordenada à partir de um iterável.
lista = [10, 4, 1, 15, -3]
lista_ordenada1 = sorted(lista)
lista_ordenada2 = lista.sort()
print('lista = ', lista, '\n')
print('lista_ordenada1 = ', lista_ordenada1)
print('lista_ordenada2 = ', lista_ordenada2)
print('lista = ', lista)

lista =  [-3, 1, 4, 10, 15] 

lista_ordenada1 =  [-3, 1, 4, 10, 15]
lista_ordenada2 =  None
lista =  [-3, 1, 4, 10, 15]


Exercício 13

In [ ]:
#Ordenando valores a partir da lógica

lista = [7, 4]
if lista[0] > lista[1]: #Se o índice zero da lista for maior que o índice um ele fará a alteração da ordem dos valores
    aux = lista[1]
    lista[1] = lista[0]
    lista[0] = aux
print(lista)


[4, 7]


Exercício 14

In [ ]:
def executar_selection_sort(lista):
    n = len(lista)#Variável que guarda o tamanho da lista
    #Precisamos de duas estruturas de controle para iterar, tanto para ir atualizando a posição de inserção 
    #quanto para achar o menor valor da lista.
    #Usamos a variável i para controlar a posição de inserção e a variável j para iterar sobre
    #os valores da lista, procurando o menor valor. A busca pelo menor valor é feita com o auxílio de
    #uma variável com a qual, quando o menor valor for encontrado, a variável index_menor guardará a
    #posição para a troca dos valores
    for i in range(0, n):
        index_menor = i
        for j in range(i+1, n):
            if lista[j] < lista[index_menor]:
                index_menor = j
        lista[i], lista[index_menor] = lista[index_menor], lista[i]#Usamos a atribuição múltipla para fazer a troca dos valores, quando necessário.
        return lista
lista = [10, 9, 5, 8, 11, -1, 3]
executar_selection_sort(lista)


[-1, 9, 5, 8, 11, 10, 3]

Exercício 14:

In [ ]:
#Bubble sort (Ordenação por "bolha")

def executar_bubble_sort(lista):
    n = len(lista)
    for i in range(n-1):
        for j in range(n-1):
            if lista[j] > lista[j + 1]:
                lista[j], lista[j + 1] = lista[j + 1], lista[j]
    return lista
lista = [10, 9, 5, 8, 11, -1, 3]
executar_bubble_sort(lista)


[-1, 3, 5, 8, 9, 10, 11]

Exercício 15:

In [ ]:
# Ordenação por inserção (insertion sort)

def executar_insertion_sort(lista):
    n = len(lista)
    for i in range(1, n):
        valor_inserir = lista[i]
        j = i - 1
        while j >= 0 and lista[j] > valor_inserir:
            lista[j + 1] = lista[j]
            j = j - 1
            lista[j + 1] = valor_inserir

    return lista
lista = [10,9,5,8,11,-1,3]
executar_insertion_sort(lista)


[-1, 3, 5, 8, 9, 10, 11]

Exercício 16

In [ ]:
# Ordenação por junção

def executar_merge_sort(lista):
    if len(lista) <= 1: return lista
    else:
        meio = len(lista) // 2
        esquerda = executar_merge_sort(lista[:meio])
        direita = executar_merge_sort(lista[meio:])
        return executar_merge(esquerda, direita)
def executar_merge(esquerda, direita):
    sub_lista_ordenada = []
    topo_esquerda, topo_direita = 0, 0
    while topo_esquerda < len(esquerda) and topo_direita < len(direita):
        if esquerda[topo_esquerda] <= direita[topo_direita]:
            sub_lista_ordenada.append(esquerda[topo_esquerda])
            topo_esquerda += 1
        else:
            sub_lista_ordenada.append(direita[topo_direita])
            topo_direita += 1
    sub_lista_ordenada += esquerda[topo_esquerda:]
    sub_lista_ordenada += direita[topo_direita:]
    return sub_lista_ordenada
lista = [10, 9, 5, 8, 11, -1, 3]
executar_merge_sort(lista)


[-1, 3, 5, 8, 9, 10, 11]

Exercício 17

In [ ]:
#Quicksort (Ordenação rápida)

def executar_quicksort(lista, inicio, fim):
    if inicio < fim:
        pivo = executar_particao(lista, inicio, fim)
        executar_quicksort(lista, inicio, pivo-1)
        executar_quicksort(lista, pivo+1, fim)
    return lista
def executar_particao(lista, inicio, fim):
    pivo = lista[fim]
    esquerda = inicio
    for direita in range(inicio, fim):
        if lista[direita] <= pivo:
            lista[direita], lista[esquerda] = lista[esquerda], lista[direita]
            esquerda += 1
    lista[esquerda], lista[fim] = lista[fim],lista[esquerda]
    return esquerda
lista = [10, 9, 5, 8, 11, -1, 3]
executar_quicksort(lista, inicio=0, fim=len(lista)-1)


[-1, 3, 5, 8, 9, 10, 11]